name: money_trader
description: Crypto and forex signal companion app
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.5
  dio: ^5.4.0
  web_socket_channel: ^2.4.0
  syncfusion_flutter_charts: ^25.1.41
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  in_app_purchase: ^3.1.11
  firebase_messaging: ^14.7.5

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
