version: '3.9'
services:
  api:
    build: ../backend
    container_name: money-trader-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ../backend/app:/app/app
    environment:
      - SECRET_KEY=dev-secret
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/money_trader
      - REDIS_URL=redis://redis:6379/0
      - DEV_MODE=true
    ports:
      - "8080:8000"
    depends_on:
      - db
      - redis
  worker:
    build: ../backend
    command: python -m app.workers.alerts_worker
    environment:
      - SECRET_KEY=dev-secret
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/money_trader
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
  feeder:
    build:
      context: ..
      dockerfile: feeder/Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=money_trader
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
volumes:
  postgres_data:
